---
- name: 作業用ユーザ作成
  user: name=ansible

- name: ディレクトリ作成
  file:
    path: /tmp/zbx
    state: directory
    owner: ansible
    group: ansible
    mode: 0755

- name: SELinux無効化
  replace:
    path: /etc/selinux/config
    regexp: '^SELINUX=enforcing'
    replace: SELINUX=disabled

- name: firewalld停止
  systemd:
    name: firewalld.service
    state: stopped
    enabled: no

