---
- name: OS再起動 
  shell: sleep 5 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0

- name: OS再起動待ち
  wait_for_connection:
  connect_timeout: 20
  sleep: 5
  delay: 5
  timeout: 60
